formatters:
  debug:
    datafmt: '%Y-%m-%d %H:%M:%S %z'
    format: '%(asctime)s - %(levelname)s - %(name)s - %(lineno)s - %(message)s'
  default:
    datafmt: '%Y-%m-%d %H:%M:%S %z'
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: debug
    stream: ext://sys.stdout
  file:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: zimtechapi.log
    formatter: debug
    maxBytes: 52428800
    mode: a
loggers:
  zimtechapi:
    handlers:
    - console
    - file
    level: DEBUG
  utils:
    handlers:
    - console
    - file
    level: DEBUG
  auth:
    handlers:
    - console
    - file
    level: DEBUG
version: 1
