[project]
name = "zimtechapi"
version = "0.1.0"
description = "Zimmer Technologies, LLC. API"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"