"""empty message

Revision ID: 5ab98f3b83e6
Revises: 
Create Date: 2023-08-15 18:28:48.634407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab98f3b83e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WEB_APP_USER',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('WEB_APP_USER_WHITE_LIST',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('WEB_APP_USER_CSRF_SESSION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('csrf_token', sa.String(length=255), nullable=False),
    sa.Column('csrf_token_expiration_datetime', sa.DateTime(), nullable=False),
    sa.Column('csrf_token_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['WEB_APP_USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csrf_token')
    )
    op.create_table('WEB_APP_USER_SESSION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('session_token_expiration_datetime', sa.DateTime(), nullable=False),
    sa.Column('session_token_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['WEB_APP_USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WEB_APP_USER_SESSION')
    op.drop_table('WEB_APP_USER_CSRF_SESSION')
    op.drop_table('WEB_APP_USER_WHITE_LIST')
    op.drop_table('WEB_APP_USER')
    # ### end Alembic commands ###
