"""empty message

Revision ID: 5ac1184812e4
Revises: 5ab98f3b83e6
Create Date: 2023-08-16 10:38:30.017207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac1184812e4'
down_revision = '5ab98f3b83e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WEB_APP_USER_WHITE_LIST', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('WEB_APP_USER_WHITE_LIST_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WEB_APP_USER_WHITE_LIST', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('WEB_APP_USER_WHITE_LIST_username_key', ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
