"""empty message

Revision ID: 7a0dc5a36aae
Revises: 79c2cdfd97f6
Create Date: 2023-06-29 23:58:25.708206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0dc5a36aae'
down_revision = '79c2cdfd97f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WEB_APP_USER',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('WEB_APP_USER_CSRF_SESSION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('csrf_token', sa.String(length=255), nullable=False),
    sa.Column('csrf_token_expiration_datetime', sa.DateTime(), nullable=False),
    sa.Column('csrf_token_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['WEB_APP_USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csrf_token')
    )
    op.create_table('WEB_APP_USER_SESSION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('session_token_expiration_datetime', sa.DateTime(), nullable=False),
    sa.Column('session_token_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['WEB_APP_USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WEB_APP_USER_SESSION')
    op.drop_table('WEB_APP_USER_CSRF_SESSION')
    op.drop_table('WEB_APP_USER')
    # ### end Alembic commands ###
